export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TOGGLE_CARD_HIDDEN = 'TOGGLE_CARD_HIDDEN';
export const ADD_ITEM = 'ADD_ITEM';
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const FETCH_SHOP_COLLECTIONS_START = 'FETCH_SHOP_COLLECTIONS_START';
export const FETCH_SHOP_COLLECTIONS_SUCCESS = 'FETCH_SHOP_COLLECTIONS_SUCCESS';
export const FETCH_SHOP_COLLECTIONS_FAILURE = 'FETCH_SHOP_COLLECTIONS_FAILURE';
